/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'asgour' at '5/15/17 11:32 AM' with Gradle 2.13
 *
 * @author asgour, @date 5/15/17 11:32 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
